Repository modorie/foxie, pull requests merged in 2021-11, with the labels that each got.

#6 [WIP] 브랜치 분리 테스트
  README.md
Labels: WIP

#9 [Feat/#8] Django 프로젝트 생성 및 설정
  api/api/__init__.py
  api/api/asgi.py
  api/api/settings.py
  api/api/urls.py
  api/api/wsgi.py
  api/manage.py
  api/requirements.txt
Labels: 🌚 BACK, ✨ FEAT

#12 [Feat/#11] Django Vue 연동
  api/api/settings.py
  api/api/urls.py
  api/articles/__init__.py
  api/articles/admin.py
  api/articles/apps.py
  api/articles/migrations/0001_initial.py
  api/articles/migrations/__init__.py
  api/articles/models.py
  api/articles/serializers.py
  api/articles/tests.py
  api/articles/urls.py
  api/articles/views.py
  api/requirements.txt
  babel.config.ts
  package-lock.json
  package.json
  postcss.config.js
  public/index.html
  src/App.vue
  src/assets/tailwind.css
  src/main.ts
  src/views/Home.vue
  tailwind.config.js
  yarn.lock
Labels: 🌚 BACK, ✨ FEAT, 🌝 FRONT

#14 [Feat/#10] Django user model 구축 및 앱 생성
  api/accounts/__init__.py
  api/accounts/admin.py
  api/accounts/apps.py
  api/accounts/forms.py
  api/accounts/migrations/__init__.py
  api/accounts/models.py
  api/accounts/tests.py
  api/accounts/urls.py
  api/accounts/views.py
  api/api/settings.py
  api/api/urls.py
  api/articles/migrations/0001_initial.py
Labels: 🌚 BACK, ✨ FEAT

#33 [WIP/#32] 백엔드 리포지토리 분리
  api/accounts/__init__.py
  api/accounts/admin.py
  api/accounts/apps.py
  api/accounts/forms.py
  api/accounts/migrations/__init__.py
  api/accounts/models.py
  api/accounts/tests.py
  api/accounts/urls.py
  api/accounts/views.py
  api/api/__init__.py
  api/api/asgi.py
  api/api/settings.py
  api/api/urls.py
  api/api/wsgi.py
  api/articles/__init__.py
  api/articles/admin.py
  api/articles/apps.py
  api/articles/migrations/__init__.py
  api/articles/models.py
  api/articles/serializers.py
  api/articles/tests.py
  api/articles/urls.py
  api/articles/views.py
  api/manage.py
  api/requirements.txt
Labels: 🥺 WIP

#36 [Feat/#35] Header + Search bar 만들기
  src/App.vue
  src/components/Header.vue
  src/components/HelloWorld.vue
  src/components/IconBase.vue
  src/components/Sidebar.vue
  src/components/icons/IconAvatar.vue
  src/components/icons/IconBell.vue
  src/components/icons/IconSearch.vue
Labels: 🎨 DESIGN, ✨ FEAT, 🌝 FRONT

#38 [Design/#37] Sidebar Styling
  src/assets/tailwind.css
  src/components/Sidebar.vue
  src/components/icons/IconCommunity.vue
  src/components/icons/IconHome.vue
  src/components/icons/IconLogo.vue
  src/components/icons/IconMovie.vue
  src/components/icons/IconReview.vue
Labels: 🎨 DESIGN, 🌝 FRONT

#40 [Feat/#39] TMDB API + 영화 페이지 레이아웃 구현
  src/App.vue
  src/assets/tailwind.css
  src/components/IconBase.vue
  src/components/MovieCard.vue
  src/components/MovieList.vue
  src/components/icons/IconStar.vue
  src/main.ts
  src/views/Movie.vue
  yarn.lock
Labels: 🎨 DESIGN, ✨ FEAT, 🌝 FRONT

#46 [Feat/#41] 영화 상세 페이지 레이아웃 구현
  src/App.vue
  src/components/Header.vue
  src/components/MovieCard.vue
  src/router/index.ts
  src/views/MovieDetail.vue
  yarn.lock
Labels: ✨ FEAT, 🌝 FRONT

#49 [Feat/#45] Sign up, Log in 구현
  src/components/Dropdown.vue
  src/components/Header.vue
  src/router/index.ts
  src/views/accounts/Login.vue
  src/views/accounts/Signup.vue
Labels: 🎨 DESIGN, ✨ FEAT, 🌝 FRONT

#53 [Feat/#22+27] 다크모드 구현 및 임시 DS 구축
  src/App.vue
  src/assets/fds.css
  src/assets/tailwind.css
  src/assets/theme.css
  src/components/Header.vue
  src/components/MovieCard.vue
  src/components/Sidebar.vue
  src/main.ts
  src/views/Movie.vue
Labels: 🎨 DESIGN, ✨ FEAT, 🌝 FRONT

#54 [design/#51] favicon 추가
  public/favi.ico
  public/index.html
Labels: 🎨 DESIGN

#57 [Feat/#43, #56] 커뮤니티 메인 & 상세 페이지 레이아웃
  package-lock.json
  package.json
  src/assets/theme.css
  src/components/Board.vue
  src/components/BoardSearchBar.vue
  src/components/Comment.vue
  src/components/CommentWrite.vue
  src/components/Dropdown.vue
  src/components/Pagination.vue
  src/components/Sidebar.vue
  src/components/icons/IconDown.vue
  src/components/icons/IconLeft.vue
  src/components/icons/IconRight.vue
  src/router/index.ts
  src/views/Community.vue
  src/views/CommunityDetail.vue
Labels: 🎨 DESIGN, ✨ FEAT, 🌝 FRONT

#58 [Feat/#55] TOAST UI 에디터를 사용한 글쓰기 페이지 구현
  package-lock.json
  package.json
  src/router/index.ts
  src/views/CommunityNew.vue
  yarn.lock
Labels: ✨ FEAT, 🌝 FRONT

#63 [Feat/#61] 프로필 페이지 레이아웃
  src/assets/theme.css
  src/components/Sidebar.vue
  src/components/icons/IconFollow.vue
  src/components/icons/IconProfile.vue
  src/router/index.ts
  src/views/Profile.vue
Labels: ✨ FEAT, 🌝 FRONT

#64 [Feat/#59] 메인페이지 레이아웃
  src/App.vue
  src/assets/theme.css
  src/components/Header.vue
  src/components/MovieCard.vue
  src/components/MovieCarousel.vue
  src/components/MovieCarouselList.vue
  src/components/MovieRecommend.vue
  src/components/MovieRecommendCard.vue
  src/views/Home.vue
  yarn.lock
Labels: 🎨 DESIGN, ✨ FEAT, 🌝 FRONT

#71 [Feat/#70] 유저 인증 시스템 Vuex로 상태관리하기
  src/components/Dropdown.vue
  src/components/Header.vue
  src/helper/index.ts
  src/router/index.ts
  src/store/index.ts
  src/views/accounts/Login.vue
  src/views/accounts/Signup.vue
Labels: ✨ FEAT, 🌝 FRONT

#69 [Feat/#68] 영화 상세 페이지 디자인
  src/App.vue
  src/assets/theme.css
  src/components/Board.vue
  src/components/BoardSearchBar.vue
  src/components/Comment.vue
  src/components/Header.vue
  src/components/MovieCard.vue
  src/components/MovieList.vue
  src/components/Pagination.vue
  src/components/Sidebar.vue
  src/views/Community.vue
  src/views/CommunityDetail.vue
  src/views/MovieDetail.vue
  src/views/Profile.vue
Labels: 🎨 DESIGN, ✨ FEAT, 🌝 FRONT

#75 [Design/#72] 로그인, 회원가입 페이지 간단한 디자인
  src/views/accounts/Login.vue
  src/views/accounts/Signup.vue
Labels: 🎨 DESIGN, 🌝 FRONT

#77 [Feat/#67] 영화 캐러셀 컴포넌트를 도입하기
  package-lock.json
  package.json
  src/components/Dropdown.vue
  src/components/Header.vue
  src/components/MovieCard.vue
  src/components/MovieCarousel.vue
  src/components/MovieCarouselList.vue
  src/components/MovieList.vue
  src/main.ts
  src/router/index.ts
  src/views/Home.vue
  src/views/Movie.vue
  src/views/MovieDetail.vue
  yarn.lock
Labels: 🎨 DESIGN, ✨ FEAT, 🌝 FRONT

#80 [WIP] module 의존성 오류 해결
  package-lock.json
  package.json
  src/main.ts
  yarn.lock
Labels: 🥺 WIP

#82 [Feat/#81] 리뷰 피드 페이지 제작
  src/assets/theme.css
  src/components/Board.vue
  src/components/ReviewCard.vue
  src/components/ReviewMovieCard.vue
  src/components/Sidebar.vue
  src/components/icons/IconComment.vue
  src/components/icons/IconHeart.vue
  src/components/icons/IconMoon.vue
  src/components/icons/IconSun.vue
  src/components/icons/IconWrite.vue
  src/views/CommunityDetail.vue
  src/views/Home.vue
  src/views/MovieDetail.vue
  src/views/Review.vue
Labels: 🎨 DESIGN, ✨ FEAT, 🌝 FRONT

#85 [Feat/#86] 페이지네이션 구현
  src/App.vue
  src/components/Board.vue
  src/components/MovieCard.vue
  src/components/MovieRecommendCard.vue
  src/components/Pagination.vue
  src/components/ReviewCard.vue
  src/components/icons/IconLeft.vue
  src/components/icons/IconRight.vue
  src/components/icons/IconStarHalf.vue
  src/views/Community.vue
  src/views/CommunityDetail.vue
  src/views/CommunityNew.vue
  src/views/Home.vue
  src/views/Movie.vue
  src/views/MovieDetail.vue
  src/views/Profile.vue
  src/views/Review.vue
  src/views/accounts/Login.vue
  src/views/accounts/Signup.vue
Labels: 🎨 DESIGN, ✨ FEAT, 🌝 FRONT

#89 [Feat/#74] 커뮤니티 페이지 연동 및 디테일 추가
  src/assets/theme.css
  src/components/Board.vue
  src/components/Comment.vue
  src/components/CommentWrite.vue
  src/components/CommunityDropdown.vue
  src/components/ReviewCard.vue
  src/components/icons/IconDots.vue
  src/store/index.ts
  src/views/CommunityDetail.vue
  src/views/CommunityNew.vue
Labels: ✨ FEAT, 🌝 FRONT

#93 [Feat/#92] 헤더 검색 기능 구현
  src/assets/theme.css
  src/components/Board.vue
  src/components/Header.vue
  src/components/MovieCard.vue
  src/components/ReviewCard.vue
  src/components/ReviewWrite.vue
  src/components/StarRating.vue
  src/components/StarRatingInput.vue
  src/components/icons/IconStarHalf.vue
  src/views/Home.vue
  src/views/MovieDetail.vue
Labels: 🎨 DESIGN, ✨ FEAT, 🌝 FRONT

#95 [Feat/#94] 영화 디테일 및 리뷰 연동
  src/components/Comment.vue
  src/components/ReviewCardSimple.vue
  src/components/ReviewDropdown.vue
  src/components/ReviewWrite.vue
  src/components/icons/IconHorizontalDots.vue
  src/views/CommunityDetail.vue
  src/views/MovieDetail.vue
Labels: 🛠 REFAC, ✨ FEAT, 🌝 FRONT

#96 [Feat/#97] 2차 피드백
  src/App.vue
  src/assets/theme.css
  src/components/Header.vue
  src/components/Modal.vue
  src/components/MovieRecommendCard.vue
  src/components/ReviewMovieCard.vue
  src/components/StarRatingInput.vue
  src/components/icons/IconMoon.vue
  src/components/icons/IconSun.vue
  src/components/icons/IconX.vue
  src/views/Community.vue
  src/views/CommunityDetail.vue
  src/views/CommunityNew.vue
  src/views/MovieDetail.vue
  src/views/accounts/Login.vue
  src/views/accounts/Signup.vue
Labels: 🎨 DESIGN, ✨ FEAT, 🌝 FRONT

#99 [Feat/#98] 프로필 페이지 연동
  src/assets/theme.css
  src/components/MovieCard.vue
  src/components/ProfileSettings.vue
  src/components/ReviewCardSimple.vue
  src/components/Sidebar.vue
  src/router/index.ts
  src/views/MovieDetail.vue
  src/views/Profile.vue
  src/views/ProfileNew.vue
Labels: ✨ FEAT, 🌝 FRONT

#103 [Feat/#102] 추천 시스템 연동
  src/assets/theme.css
  src/components/MovieRecommend.vue
  src/components/MovieRecommendActors.vue
  src/components/MovieRecommendFollowings.vue
  src/components/MovieRecommendMovies.vue
  src/components/MovieRecommendPreview.vue
  src/views/accounts/Login.vue
Labels: ✨ FEAT, 🌝 FRONT

#105 [Feat/#104] 리뷰 피드 페이지 연동
  src/components/ReviewCard.vue
  src/components/ReviewCardSimple.vue
  src/components/ReviewComment.vue
  src/components/ReviewCommentWrite.vue
  src/components/ReviewDropdown.vue
  src/components/ReviewMovieCard.vue
  src/store/index.ts
  src/views/Review.vue
  src/views/accounts/Login.vue
Labels: ✨ FEAT, 🌝 FRONT

#101 [Feat/#100] 3차 피드백
  src/App.vue
  src/assets/theme.css
  src/components/Board.vue
  src/components/CommunityCardHome.vue
  src/components/Header.vue
  src/components/IconBase.vue
  src/components/Modal.vue
  src/components/ReviewCardHome.vue
  src/components/Sidebar.vue
  src/components/icons/IconMedalBronze.vue
  src/components/icons/IconMedalGold.vue
  src/components/icons/IconMedalSilver.vue
  src/components/icons/IconRight.vue
  src/main.ts
  src/views/Community.vue
  src/views/CommunityDetail.vue
  src/views/CommunityEdit.vue
  src/views/CommunityNew.vue
  src/views/Home.vue
  src/views/Movie.vue
  src/views/MovieDetail.vue
  src/views/ProfileNew.vue
  src/views/Review.vue
Labels: 🎨 DESIGN, ✨ FEAT, 🌝 FRONT

#107 [Feat/#106] 마지막 피드백
  src/App.vue
  src/assets/fds.css
  src/components/Board.vue
  src/components/BoardSearchBar.vue
  src/components/Comment.vue
  src/components/CommentWrite.vue
  src/components/CommunityCardHome.vue
  src/components/Dropdown.vue
  src/components/Header.vue
  src/components/Modal.vue
  src/components/MovieRecommend.vue
  src/components/MovieRecommendActors.vue
  src/components/MovieRecommendFollowings.vue
  src/components/MovieRecommendMovies.vue
  src/components/Pagination.vue
  src/components/ProfileDashboard.vue
  src/components/ProfileSettings.vue
  src/components/ReviewCard.vue
  src/components/ReviewCardHome.vue
  src/components/ReviewCardSimple.vue
  src/components/ReviewComment.vue
  src/components/ReviewCommentWrite.vue
  src/components/ReviewMovieCard.vue
  src/components/ReviewWrite.vue
  src/components/Sidebar.vue
  src/components/StarRatingInput.vue
  src/views/Community.vue
  src/views/CommunityDetail.vue
  src/views/CommunityEdit.vue
  src/views/CommunityNew.vue
  src/views/Home.vue
  src/views/MovieDetail.vue
  src/views/Profile.vue
  src/views/ProfileNew.vue
  src/views/Review.vue
  src/views/accounts/Login.vue
Labels: 🛠 REFAC, 🎨 DESIGN, ✨ FEAT, 🌝 FRONT

#113 [Docs/#108] 리드미 작성
  README.md
Labels: 📚 DOCS

#115 [Docs/#114] 리드미 내용 추가
  README.md
Labels: 📚 DOCS
